### ISSUE TITLE
Incompatible VeraCrypt version

### ISSUE THREAD

**Issue by siryoav** [th-wilde/veracrypt-w10-patcher#12]
After updating(1607 -> 1709) and booting **successfully** I got a message from VeraCrypt(after login in to my user) that there is an "incompatible VeraCrypt version installed" (The message is much longer).

This was happening immediately on login(auto start) and also when trying to start VeraCrypt software manually .

Rebooting didn't help(although no problem to boot up - In general - the update was successful).

The Fix:
Open the VeraCrypt installation file, and did "Upgrade" to the installation, which fixed the issue.

**Comment by th-wilde** [comment]
This seems to me like a outcome if the installed version of veracrypt differ from the one that is patched inside the windows installation media. This can easily accrue if the same media is used to upgrade multiple machines. The patcher takes the Veracrypt driver from the system where it's running. If this version differs from the machine that later gets upgraded with it, than this type of error makes sense to me. 
On a single machine this shouln't happen, except Veracrypt is updated between patching and upgrading with the patched media.

I recommend to upgrade Veracrypt to the newest version (if a newer exist) before patching. To upgrade multiple machines, just ensure that they get have the same (probably newer) Veracrypt version installed before starting the upgrade. If a machine has already a newer version installed, i recommend to update the installation media (create a new one with the patcher) instead of downgrading the installed Veracrypt version to get them match.
