### ISSUE TITLE
UEFI: load EFI bootfile from stick - script working?

### ISSUE THREAD

**Issue by david-camden** [th-wilde/veracrypt-w10-patcher#18]
hi th wilde,
thanks for this nice script.
i am preparing to upgrade to 1803 which should work properly according to the hall of fame.
but i have a special problem:
each time i boot i need to plugin an usb stick with the veracrypt efi bootloader because somehow it didnt put it on harddisk properly while encrypting system.
the pretest failed and then i did the trick with the usb bootloader which passed the pretest. then it encrypted the drive properly but each time i have to use the stick now, otherwise it tries to repair the bootloader by windows.
is it possible to use your script without danger of shooting the system? how can i provide the veracrypt bootloader for the iso then? simply booting like everytime with efi from stick?

i must add i had to change the booting mechanism from uefi to normal (legacy) to make it even work.

**Comment by th-wilde** [comment]
Hi david-camden,

i can't say with certainty that it will work. There are many users that had trouble to upgrade by a normal operating UEFI setup. There a many pitfalls (specially in UEFI setups) that can cause trouble. The condition of your system seems critical to me. So it's probably more likely that the upgrade fail. Specially because the upgrade require the windows bootloder to be present (but unused due to veracrypt own one) or it will roll back (that was the behavior back from 1607 to 1703) for UEFI setups. Since you said you had to change settings for "legacy boot" (Compatibility Support Module; CSM; aka BIOS-Mode), I have totally no clue how your system manages it to boot at all.

Unless you don't fear to probably corrupt the system and might lose all encrypted data (from with the important data should always backed up) , I can't recommend to upgrade this way. Consider to decrypt the system, upgrade normally and encrypt it again. This way has also no guarantee to work, but a recovery is more likely to work on a non encrypted system than on an encrypted one. And maybe the new process of encrypting the system fixes your boot problem.
