### ISSUE TITLE
i have a probleme with my second disk (i can mount it without password)

### ISSUE THREAD

**Issue by floflo530** [th-wilde/veracrypt-w10-patcher#24]
hi, i make a video -> 
https://youtu.be/h4w7OXZ07cA

When i unmount for the second time en mount i need password but not the first times after reboot.

i need help 👯

**Comment by th-wilde** [comment]
I know it's a long time.
In the settings for system encryption is a option to copy the password into the memory of the driver. This is usually activated to prevent additional password props. Containers with the same password can than mounted without entering the password.

Another idea is that (since windows 10 is usually just kills all programs of the user and than hibernates the system on shutdowns) the password of the last time is still in the memory after hibernation and so veracrypt can use it right away. Try a newer VeraCrypt version i possible or try disabling hibernation.
